version: '3.4'

services:
  app:
    image: ghcr.io/eclipse-opensmartclide/smartclide/smartclide-ide:1.2
    ports:
      - '8080:8080'
    depends_on:
      - mongo
    environment:
      ROOT_URL: ${APP_ROOT_URL:-http://localhost}
      MONGO_URL: mongodb://mongo:27017/meteor
      PORT: 8080
      KEYCLOAK_URL:
      KEYCLOAK_REALM:
      KEYCLOAK_CLIENT_ID:
      CHE_URL: https://che-smartclide-che.che.smartclide.eu
      SMARTCLIDE_BACKEND_URL: https://api.dev.smartclide.eu
      JBPM_URL: https://jbpm.dev.smartclide.eu/business-central/kie-wb.jsp
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M
  mongo:
    image: mongo:4.0.27-xenial
    command:
      - --storageEngine=wiredTiger
    volumes:
      - mongodata:/data/db

volumes:
  mongodata:
